#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

PACKAGE_NAME="drovr"
BOOTSTRAP_VERSION="0.1.0"
BOOTSTRAP_TAG="v0.1.0"
GITHUB_OWNER="ricardogzm"
GITHUB_REPO="drovr"
WORKFLOW_FILENAME="package-release.yml"
SECRET_NAME="NPM_TOKEN"

banner "Drovr 0.1.0 Bootstrap and OIDC Cutover"

# ── Helper functions for verification and state checks ───────────────────

_check_command() {
  local cmd="$1" label="$2"
  if command -v "$cmd" >/dev/null 2>&1; then
    printf '    %s✓%s %s (%s)\n' "$GREEN" "$RESET" "$label" "$(command -v "$cmd")"
    return 0
  else
    printf '    %s✗%s %s is not installed\n' "$RED" "$RESET" "$label"
    return 1
  fi
}

_is_npm_published() {
  local pkg="$1" ver="$2"
  local view_out
  view_out=$(npm view "${pkg}@${ver}" version 2>/dev/null || true)
  [[ "$view_out" == "$ver" ]]
}

_is_github_secret_present() {
  local secret="$1"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    local list_out
    if list_out=$(gh secret list --repo "${GITHUB_OWNER}/${GITHUB_REPO}" 2>/dev/null); then
      printf '%s\n' "$list_out" | grep -E "^${secret}[[:space:]]" >/dev/null 2>&1
      return
    fi
  fi
  return 1
}

_is_github_release_public() {
  local tag="$1"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    local rel_json
    rel_json=$(gh release view "$tag" --repo "${GITHUB_OWNER}/${GITHUB_REPO}" --json isDraft,isPrerelease 2>/dev/null || true)
    if [[ -n "$rel_json" ]]; then
      local is_draft is_prerelease
      is_draft=$(printf '%s' "$rel_json" | grep -o '"isDraft":true' || true)
      is_prerelease=$(printf '%s' "$rel_json" | grep -o '"isPrerelease":true' || true)
      [[ -z "$is_draft" && -z "$is_prerelease" ]]
      return
    fi
  fi
  return 1
}

# ── Stage 1: Pre-flight checks ───────────────────────────────────────────
stage "Pre-flight checks — Authentication & Tools"
say "Verifying local development environment and CLI authentication."

PREFLIGHT_OK=1

say "Checking required tools:"
_check_command git "Git CLI" || PREFLIGHT_OK=0
_check_command gh "GitHub CLI (gh)" || PREFLIGHT_OK=0
_check_command npm "npm CLI" || PREFLIGHT_OK=0
_check_command node "Node.js (Node 24+)" || PREFLIGHT_OK=0
_check_command pnpm "pnpm" || PREFLIGHT_OK=0

say "Checking CLI authentication:"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  GH_USER=$(gh api user -q .login 2>/dev/null || gh auth status 2>&1 | grep -o "account [^ ]*" | head -n1 | cut -d' ' -f2 || echo "authenticated")
  printf '    %s✓%s GitHub CLI authenticated as %s%s%s\n' "$GREEN" "$RESET" "$BOLD" "$GH_USER" "$RESET"
else
  printf '    %s✗%s GitHub CLI is not authenticated (run: %sgh auth login%s)\n' "$RED" "$RESET" "$BOLD" "$RESET"
  PREFLIGHT_OK=0
fi

if command -v npm >/dev/null 2>&1; then
  NPM_USER=$(npm whoami 2>/dev/null || true)
  if [[ -n "$NPM_USER" ]]; then
    printf '    %s✓%s npm CLI authenticated as %s%s%s\n' "$GREEN" "$RESET" "$BOLD" "$NPM_USER" "$RESET"
  else
    printf '    %s✗%s npm CLI is not logged in (run: %snpm login%s)\n' "$RED" "$RESET" "$BOLD" "$RESET"
    PREFLIGHT_OK=0
  fi
fi

if [[ "$PREFLIGHT_OK" -eq 0 ]]; then
  warn "Pre-flight checks failed. Please install missing tools and authenticate, then re-run."
  if [[ "${1:-}" == "--check-only" ]]; then
    exit 1
  fi
  pause "Press Enter after resolving authentication to continue (or Ctrl-C to abort)"
else
  printf '\n  %s✓ All pre-flight checks passed.%s\n\n' "$GREEN" "$RESET"
  if [[ "${1:-}" == "--check-only" ]]; then
    exit 0
  fi
  pause "Continue to package identity verification"
fi

# ── Stage 2: Package Identity Check ───────────────────────────────────────
stage "Package Identity — Verify npm registry state"
say "Verifying that the unscoped npm package 'drovr' is ready for initial bootstrap."

NPM_STATUS="absent"
NPM_VIEW_OUTPUT=$(npm view drovr --json 2>/dev/null || true)

if [[ -z "$NPM_VIEW_OUTPUT" || "$NPM_VIEW_OUTPUT" == *"E404"* || "$NPM_VIEW_OUTPUT" == *"404 Not Found"* ]]; then
  printf '  %s✓ Package drovr is absent on npm (expected for initial bootstrap).%s\n\n' "$GREEN" "$RESET"
  note "Initial 0.1.0 publication will establish package ownership on npm under your account."
  pause "Continue to bootstrap credential setup"
else
  # Package exists on npm. Check if version 0.1.0 is already published.
  EXISTING_VERSION=$(npm view drovr version 2>/dev/null || true)
  if [[ "$EXISTING_VERSION" == "$BOOTSTRAP_VERSION" ]]; then
    printf '  %sℹ Package drovr is already published at version %s.%s\n' "$BLUE" "$BOOTSTRAP_VERSION" "$RESET"
    note "Recognized completed publication. Subsequent stages will verify artifacts and complete OIDC cutover."
    NPM_STATUS="published"
    pause "Continue to next stage"
  else
    warn "Package 'drovr' already exists on npm at unexpected version '${EXISTING_VERSION}'."
    say "Initial bootstrap requires an absent package or an already-published version ${BOOTSTRAP_VERSION}."
    note "Check npm package ownership or name collisions: https://www.npmjs.com/package/drovr"
    exit 1
  fi
fi

# ── Stage 3: Temporary Bootstrap Credential ──────────────────────────────
stage "Bootstrap Credential — Granular npm token"

if [[ "$NPM_STATUS" == "published" ]]; then
  printf '  %s✓ drovr@0.1.0 is already published on npm registry.%s\n' "$GREEN" "$RESET"
  note "Skipping bootstrap token creation (already published)."
  pause "Continue to Package Release verification"
else
  say "npm requires a package to exist before configuring GitHub Actions OIDC Trusted Publishing."
  say "We'll create a temporary, granular token with write access for the initial 0.1.0 publish only."
  say "This token will be revoked and deleted immediately after 0.1.0 is published."
  printf '\n'

  open_url "https://www.npmjs.com/settings/tokens"

  step "In npm Access Tokens, click 'Generate New Token' → 'Granular Access Token'."
  step "Token Name: drovr-0.1.0-bootstrap"
  step "Expiration: 1 day (or shortest available time-limited duration)"
  step "Permissions: Packages and scopes → Read and write"
  step "Packages: Select 'All packages' or unscoped packages under your account"
  step "Organizations: None"
  step "Click 'Generate Token' and copy the secret value."
  printf '\n'

  ask_secret NPM_TOKEN "Paste the granular npm token:"

  if [[ -z "${NPM_TOKEN:-}" ]]; then
    warn "No token entered. If already configured in GitHub Secrets, you can continue."
  else
    set_secret NPM_TOKEN "$NPM_TOKEN"
    note "Secret NPM_TOKEN written directly to GitHub repository ${GITHUB_OWNER}/${GITHUB_REPO}."
    note "Token is never stored in repository files, environment files, or logs."
  fi

  pause "Continue to Package Release authorization"
fi

# ── Stage 4: Authorize & Monitor 0.1.0 Package Release ───────────────────
stage "Authorize & Monitor 0.1.0 Package Release"

if [[ "$NPM_STATUS" == "published" ]] && _is_github_release_public "$BOOTSTRAP_TAG"; then
  printf '  %s✓ 0.1.0 Package Release is already published and public on GitHub.%s\n' "$GREEN" "$RESET"
  note "Skipping Package Release trigger stage."
  pause "Continue to Package Release verification"
else
  say "The Package Release workflow is fully automated via Release Please and .github/workflows/package-release.yml."
  say "Do not publish manually or bypass the reviewed Package Release PR."
  printf '\n'

  open_url "https://github.com/ricardogzm/drovr/pulls"

  step "Review and merge the 0.1.0 Package Release PR generated by Release Please on 'main'."
  step "Merging to 'main' triggers .github/workflows/package-release.yml."
  printf '\n'

  open_url "https://github.com/ricardogzm/drovr/actions/workflows/package-release.yml"

  step "Monitor the 'Package Release' workflow run on 'main'."
  step "Wait for the 'publish-package' job to complete (runs tests, verifies tarball, and publishes to npm)."
  printf '\n'

  if ! confirm "Has the 0.1.0 Package Release workflow run completed successfully on GitHub Actions?"; then
    warn "Workflow has not completed yet. Check logs at:"
    note "  https://github.com/ricardogzm/drovr/actions/workflows/package-release.yml"
    say "Once the workflow finishes successfully, re-run this wizard to complete OIDC cutover."
    exit 1
  fi
fi

# ── Stage 5: Artifact Verification ───────────────────────────────────────
stage "Artifact Verification — 0.1.0 Package Release"
say "Verifying public npm package, provenance, git tag, and GitHub Release."
printf '\n'

VERIFY_FAILED=0

# 1. Check public npm publication
say "Checking npm registry for drovr@0.1.0:"
if _is_npm_published "drovr" "$BOOTSTRAP_VERSION"; then
  printf '    %s✓%s Public npm package drovr@0.1.0 is live on npm registry\n' "$GREEN" "$RESET"
else
  printf '    %s✗%s Public npm package drovr@0.1.0 not found on registry\n' "$RED" "$RESET"
  VERIFY_FAILED=1
fi

# 2. Check provenance / attestations
say "Checking provenance and source attestations:"
NPM_ATTESTATIONS=$(npm view drovr@0.1.0 dist.attestations --json 2>/dev/null || true)
if [[ -n "$NPM_ATTESTATIONS" && "$NPM_ATTESTATIONS" != "null" && "$NPM_ATTESTATIONS" != "{}" && "$NPM_ATTESTATIONS" != "undefined" && "$NPM_ATTESTATIONS" != "[]" ]]; then
  printf '    %s✓%s Provenance attestations verified for drovr@0.1.0 on npm\n' "$GREEN" "$RESET"
else
  printf '    %s✗%s Provenance attestations missing for drovr@0.1.0 on npm\n' "$RED" "$RESET"
  VERIFY_FAILED=1
fi
# 3. Check immutable git tag
say "Checking immutable git tag v0.1.0:"
if git rev-parse "$BOOTSTRAP_TAG" >/dev/null 2>&1; then
  TAG_SHA=$(git rev-parse "$BOOTSTRAP_TAG")
  printf '    %s✓%s Git tag %s exists locally (commit %s)\n' "$GREEN" "$RESET" "$BOOTSTRAP_TAG" "${TAG_SHA:0:7}"
elif command -v gh >/dev/null 2>&1 && gh api "repos/${GITHUB_OWNER}/${GITHUB_REPO}/git/refs/tags/${BOOTSTRAP_TAG}" >/dev/null 2>&1; then
  printf '    %s✓%s Git tag %s exists on remote\n' "$GREEN" "$RESET" "$BOOTSTRAP_TAG"
else
  printf '    %s✗%s Git tag %s was not found\n' "$RED" "$RESET" "$BOOTSTRAP_TAG"
  VERIFY_FAILED=1
fi

# 4. Check public GitHub Release
say "Checking public GitHub Release v0.1.0:"
if _is_github_release_public "$BOOTSTRAP_TAG"; then
  printf '    %s✓%s GitHub Release %s is public (draft: false, prerelease: false)\n' "$GREEN" "$RESET" "$BOOTSTRAP_TAG"
else
  printf '    %s✗%s GitHub Release %s is not public, is draft/prerelease, or was not found\n' "$RED" "$RESET" "$BOOTSTRAP_TAG"
  VERIFY_FAILED=1
fi

# 5. Check release notes structure
say "Checking release notes structure:"
if command -v gh >/dev/null 2>&1; then
  REL_BODY=$(gh release view "$BOOTSTRAP_TAG" --repo "${GITHUB_OWNER}/${GITHUB_REPO}" --json body -q .body 2>/dev/null || true)
  if [[ -n "$REL_BODY" ]] && printf '%s\n' "$REL_BODY" | grep -F "Full Changelog" >/dev/null 2>&1 && printf '%s\n' "$REL_BODY" | grep -E "^### (Breaking Changes|Added|Changed|Fixed|Removed)" >/dev/null 2>&1; then
    printf '    %s✓%s Canonical release notes present for %s with agreed sections\n' "$GREEN" "$RESET" "$BOOTSTRAP_TAG"
  else
    printf '    %s✗%s GitHub Release %s release notes missing agreed heading structure (### Breaking Changes/Added/Changed/Fixed/Removed + Full Changelog)\n' "$RED" "$RESET" "$BOOTSTRAP_TAG"
    VERIFY_FAILED=1
  fi
else
  printf '    %s✗%s gh CLI required to verify release notes structure\n' "$RED" "$RESET"
  VERIFY_FAILED=1
fi

# 6. Check matching version
say "Checking version consistency:"
REL_TAG_NAME=""
if command -v gh >/dev/null 2>&1; then
  REL_TAG_NAME=$(gh release view "$BOOTSTRAP_TAG" --repo "${GITHUB_OWNER}/${GITHUB_REPO}" --json tagName -q .tagName 2>/dev/null || true)
fi
if [[ "$REL_TAG_NAME" == "$BOOTSTRAP_TAG" ]] && _is_npm_published "drovr" "$BOOTSTRAP_VERSION"; then
  printf '    %s✓%s npm version %s matches GitHub Release tag %s\n' "$GREEN" "$RESET" "$BOOTSTRAP_VERSION" "$BOOTSTRAP_TAG"
else
  printf '    %s✗%s Version mismatch between npm %s and GitHub Release tag %s\n' "$RED" "$RESET" "$BOOTSTRAP_VERSION" "$BOOTSTRAP_TAG"
  VERIFY_FAILED=1
fi

printf '\n'
if [[ "$VERIFY_FAILED" -eq 1 ]]; then
  warn "Verification of 0.1.0 Package Release artifacts failed."
  say "Recovery instruction: Check the Package Release workflow logs at:"
  note "  https://github.com/ricardogzm/drovr/actions/workflows/package-release.yml"
  say "Resolve publication errors in the workflow run, then re-run this wizard."
  exit 1
else
  printf '  %s✓ 0.1.0 Package Release verified across npm, git, and GitHub.%s\n\n' "$GREEN" "$RESET"
  pause "Continue to OIDC Trusted Publishing setup"
fi

# ── Stage 6: Configure npm Trusted Publishing (OIDC) ─────────────────────
stage "OIDC Configuration — npm Trusted Publishing"
say "Now that 'drovr' exists on npm, configure GitHub Actions Trusted Publishing."
say "Subsequent Package Releases will authenticate automatically via OIDC tokens (no static secrets)."
printf '\n'

open_url "https://www.npmjs.com/package/drovr/access"

step "Navigate to 'Publishing Access' → 'Trusted Publishers'."
step "Click 'Add trusted publisher' and select 'GitHub Actions'."
step "Configure the exact repository parameters:"
printf '      %sGitHub Organization / User:%s  ricardogzm\n' "$BOLD" "$RESET"
printf '      %sRepository name:%s             drovr\n' "$BOLD" "$RESET"
printf '      %sWorkflow filename:%s           package-release.yml\n' "$BOLD" "$RESET"
printf '      %sEnvironment:%s                 (leave blank)\n' "$BOLD" "$RESET"
printf '      %sAllowed actions:%s             Select "npm publish"\n' "$BOLD" "$RESET"
step "Click 'Add publisher' to save the OIDC connection."
printf '\n'

if ! confirm "Have you configured the Trusted Publisher on npm for ricardogzm/drovr and package-release.yml with npm publish permission?"; then
  warn "Trusted publishing must be configured before deleting the bootstrap secret."
  say "Aborting. Configure Trusted Publishing on npm (https://www.npmjs.com/package/drovr/access), then re-run this wizard."
  exit 1
fi

pause "Continue to secret cleanup and token revocation"

# ── Stage 7: Cutover & Cleanup ───────────────────────────────────────────
stage "Cutover & Cleanup — Revoke bootstrap token"
say "Completing the cutover to OIDC-only publication:"
say "1. Delete GitHub Actions repository secret 'NPM_TOKEN'"
say "2. Revoke the temporary granular bootstrap token on npm"
printf '\n'

if ! confirm "Ready to delete GitHub repository secret NPM_TOKEN and revoke bootstrap token?"; then
  warn "Cutover paused. Re-run this wizard any time to finalize cleanup."
  exit 1
fi

# Delete GitHub secret
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  if _is_github_secret_present "NPM_TOKEN"; then
    if gh secret delete NPM_TOKEN --repo "${GITHUB_OWNER}/${GITHUB_REPO}" >/dev/null 2>&1; then
      printf '  %s✓ Deleted GitHub Actions secret %s.%s\n' "$GREEN" "NPM_TOKEN" "$RESET"
    else
      warn "Failed to delete secret NPM_TOKEN via gh. Delete it manually in repo Settings → Secrets."
    fi
  else
    printf '  %s✓ GitHub secret %s is already absent.%s\n' "$GREEN" "NPM_TOKEN" "$RESET"
  fi
fi

# Open npm tokens for revocation
open_url "https://www.npmjs.com/settings/tokens"

step "In npm Access Tokens, locate the temporary token (drovr-0.1.0-bootstrap)."
step "Click the trash/revoke icon to permanently revoke the token."
printf '\n'

if ! confirm "Have you revoked the temporary granular token on npm?"; then
  warn "Token revocation was not confirmed."
  say "Please revoke the bootstrap token at https://www.npmjs.com/settings/tokens, then re-run this wizard to finalize."
  exit 1
fi

# Verify GitHub secret absence
printf '\n'
say "Verifying GitHub repository secrets:"
SECRET_LIST_OUTPUT=""
if SECRET_LIST_OUTPUT=$(gh secret list --repo "${GITHUB_OWNER}/${GITHUB_REPO}" 2>/dev/null); then
  if printf '%s\n' "$SECRET_LIST_OUTPUT" | grep -E "^NPM_TOKEN[[:space:]]" >/dev/null 2>&1; then
    warn "Secret NPM_TOKEN is still present in GitHub repository ${GITHUB_OWNER}/${GITHUB_REPO}."
    say "Please delete it manually: gh secret delete NPM_TOKEN --repo ${GITHUB_OWNER}/${GITHUB_REPO}"
    exit 1
  else
    printf '  %s✓ Confirmed: Secret NPM_TOKEN is absent from %s/%s.%s\n' "$GREEN" "$GITHUB_OWNER" "$GITHUB_REPO" "$RESET"
  fi
else
  warn "Could not verify GitHub repository secrets via gh CLI."
  say "Please verify manually in repository Settings → Secrets that NPM_TOKEN has been deleted."
  exit 1
fi

printf '\n'
printf '  %s✓ OIDC Cutover Complete!%s\n' "$BOLD$GREEN" "$RESET"
say "All future Package Releases of 'drovr' will authenticate exclusively through"
say "GitHub Actions OIDC (tokenless authentication via npm Trusted Publishing)."
printf '\n'

pause "View setup summary"

finish
